# Python "numpy" kütüphanesinin kullanımı

Numpy kütüphanesi Python'da birçok nümerik işlemi ve matris operasyonlarını etkin bir şekilde yapabilmemizi sağlar.<br>


<div class="alert alert-info">
<b> DİZİLER (ARRAYS) </b> 
</div> <br>

numpy dizileri Python listelerine benzer. Temel özellikleri şunlardır
* Hepsi aynı tipte olmalıdır
* Pozitif olan "integer tuple" yapıları ile indekslenirler
* Liste kullanarak "numpy" dizisi yaratabiliriz
* Elemanlarına köşeli parantez kullanarak erişim sağlanabilir.

In [2]:
import numpy as np

In [5]:
a_numpy_array = np.array([1,5,3,9,7,5])
a_numpy_array
#numoy dizi sınıfının ismi ndarray(n-dimensional array)

array([1, 5, 3, 9, 7, 5])

In [4]:
a_numpy_array[2]

3

In [6]:
a_numpy_array.ndim

1

`ndarray` sınıfın en önemli özellikleri

>`ndim`: Eksen sayısını bellirten özellik

In [10]:
# 2 eksen
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [12]:
# 3 eksen
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)
print(x.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [13]:
# 3 eksen
x = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
3
(2, 3, 3)


In [17]:
x[0,2,2]

9

In [7]:
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
a.ndim
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [13]:
a[1,0,0,2]

3

In [16]:
print(a.shape)
print(a.size)

(2, 2, 2, 3)
24


In [17]:
a.dtype

dtype('int32')

In [19]:
b = np.array([1,2],dtype=np.int16)
c = np.array([1,2],dtype=np.float64)
print(b)
print(b.dtype)
print(c)
print(c.dtype)

[1 2]
int16
[1. 2.]
float64


In [20]:
print(b.itemsize)
print(c.itemsize)

2
8


Matrislerin satırlarını listeler halinde veriyoruz. 

Bu listelerin boyutlarının birbirine eşit olmasına dikkat etmemiz gerekiyor aksi takdirde istediğimiz matrisi yaratamayız. 

Fakat `numpy` yine de bunları listeye çevirir.

In [21]:
# Diyelim ki bir satır diğerinden boyut olarak fazla oldu
c_numpy_array = np.array([[2,3,4],[4,5,6,7]])

print(c_numpy_array)


[list([2, 3, 4]) list([4, 5, 6, 7])]


In [22]:
c_numpy_array[0][0]

2

**Dizi yaratma fonksiyonları**

numpy kütüphanesinin dizi yaratmak için hazır fonksiyonları mevcuttur. 

Aşağıda en sık kullanılanlardan örnek vermek isiyorum.

In [26]:
print("\nSıfır matris")
print(np.zeros((3,2,3)))


Sıfır matris
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [30]:
print("\nBirler Matrisi")
print(np.ones((3,3,3)))


Birler Matrisi
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
print("\nSabit Matrisi")
print(np.full((3,3),42))


Sabit Matrisi
[[42 42 42]
 [42 42 42]
 [42 42 42]]


In [36]:
print("\nIdentity matris")
print(np.eye(3))


Identity matris
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# Rasgele matris
print("\nRasgele matris")
print(np.random.random((3,3)))


Rasgele matris
[[0.93449445 0.0109167  0.74103105]
 [0.70420527 0.69670461 0.94522332]
 [0.49980837 0.64727683 0.44977899]]


Üç boyut özellikle önemli çünkü deep learning CV konusunda genelde 3 boyut üzerinden çalışılır

In [40]:
n_boyut = np.zeros((3,3,3))
# print(n_boyut)
print(n_boyut.ndim)

3


4 boyutlu diziyi resim listesi olarak düşünebilirsiniz. 

Ama bu boyut kavramı büyüdükçe işler karışmaya başlar ve kafada canlandırabilmek zorlaşır.

**np.empty() fonksiyonu**

Bu fonksiyon yeni bir dizi yaratır fakat dizinin içini 0'lar veya 1'ler ile doldurmaz 

In [41]:
a = np.empty((2,4))
print(a)

[[0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 4.15e-321 0.00e+000 0.00e+000]]


**Kesit alma**

Matrisleri parçalamak için kesit alma operatörleri kullanılabilir.

In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
2


>Kesit Alma İşlemi

In [3]:
#kesit alma
print(a[0:3,1:3])
b = a[1:3,2]
print(b)

[[2 3]
 [5 6]
 [8 9]]
[6 9]


In [4]:
print(a[2,:])

[7 8 9]


In [7]:
print(a[0:3,2])

[3 6 9]


In [9]:
#(0,0)(1,1),(2,2)
print(a[(0,1,2),(0,1,2)])

[1 5 9]


In [10]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

**np.arange() fonksiyonu**

Bu fonksiyon ardışık bir dizi oluşturur. !! Son eleman diziye dahil değildir !!

In [12]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [15]:
print(np.arange(1,30,2))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


**np.linspace() fonksiyonu**

Bu fonsiyon np.arange() fonksiyonuna benzer. Farklı olarak verilen iki sayı arasını istenilen nokta sayısı ile doldurur. Örneğin 1 ile 10 arasında 20 nokta sayı istersek aralıkları otomatik olarak hesaplar ve bize istediğimiz diziyi döndürür.

In [22]:
print(np.linspace(1,90,100))

[ 1.          1.8989899   2.7979798   3.6969697   4.5959596   5.49494949
  6.39393939  7.29292929  8.19191919  9.09090909  9.98989899 10.88888889
 11.78787879 12.68686869 13.58585859 14.48484848 15.38383838 16.28282828
 17.18181818 18.08080808 18.97979798 19.87878788 20.77777778 21.67676768
 22.57575758 23.47474747 24.37373737 25.27272727 26.17171717 27.07070707
 27.96969697 28.86868687 29.76767677 30.66666667 31.56565657 32.46464646
 33.36363636 34.26262626 35.16161616 36.06060606 36.95959596 37.85858586
 38.75757576 39.65656566 40.55555556 41.45454545 42.35353535 43.25252525
 44.15151515 45.05050505 45.94949495 46.84848485 47.74747475 48.64646465
 49.54545455 50.44444444 51.34343434 52.24242424 53.14141414 54.04040404
 54.93939394 55.83838384 56.73737374 57.63636364 58.53535354 59.43434343
 60.33333333 61.23232323 62.13131313 63.03030303 63.92929293 64.82828283
 65.72727273 66.62626263 67.52525253 68.42424242 69.32323232 70.22222222
 71.12121212 72.02020202 72.91919192 73.81818182 74

**Mantıksal indeksleme**

Matriste belirli koşulu sağlayan elemanların bulunmasını sağlar

In [23]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(a>5)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [26]:
print(a[a>5])

[ 6  7  8  9 10 11 12]


In [27]:
a[a>5] = 0
print(a)

[[1 2 3 4]
 [5 0 0 0]
 [0 0 0 0]]


>`where` fonksiyonu da mantıksal indeksleme için kullanılabilir

In [34]:
a = np.array([1,2,3,4,5])
print(np.where(a>3))
a[np.where(a>3)]

(array([3, 4], dtype=int64),)


array([4, 5])

<div class="alert alert-info">
<b> DİZİLERDE MATEMATİK İŞLEMLERİ </b> 
</div>

**Eleman bazında yapılan işlemler** 

In [52]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6]])


In [41]:
print("\nA + B")
print(a + b)


A + B
[[ 2  4  6]
 [ 8 10 12]]


In [42]:
print("\nA - B")
print(a - b)


A - B
[[0 0 0]
 [0 0 0]]


In [54]:
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [55]:
A/B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
print("\nKarekök alma sqrt(A)")
print(np.sqrt(A))


Karekök alma sqrt(A)
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


**Farklı tipteki matrislerin eklenmesi**

Bu tip bir durumda sonuç hassas olan veri tipinde oluşturulur. Örneğin : 

In [61]:
A = np.ones(3,dtype=np.int32)
B = np.ones(3,dtype=np.float64)

C = A + B
print(C)
C.dtype

[2. 2. 2.]


dtype('float64')

**Matris işlemleri**

In [67]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A,"\n\n",B)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


In [69]:
print("Matris çarpımı (Dot product) A.dot(B) ")
print(B.dot(A))

Matris çarpımı (Dot product) A.dot(B) 
[[23 34]
 [31 46]]


In [68]:
print("veya np.dot(A,B)")
print(np.dot(A,B))

veya np.dot(A,B)
[[19 22]
 [43 50]]


In [72]:
# veya A @ B
print("A@B")
print(A @ B)

A@B
[[19 22]
 [43 50]]


Transpose alma

Satırları sütun veya sütunları satır haline getirme işlemidir.

In [73]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("Transpose alma A.T")
print(A.T)

[[1 2 3]
 [4 5 6]]
Transpose alma A.T
[[1 4]
 [2 5]
 [3 6]]


**Matrisin tersini alma**

In [79]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
np.linalg.inv(a)#@a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Matrisin izini bulma**

In [82]:
a = np.array([[1,2] , [1,2]])
print(a)
np.trace(a)

[[1 2]
 [1 2]]


3

**Matrisin eigen değerlerini bulma**

In [83]:
a = np.array([[1,2] , [1,2]])
np.linalg.eig(a)

(array([0., 3.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

**$Ax = b$ şeklindeki bir denklemi çözme**

In [84]:
A = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5], [7]])
np.linalg.solve(A,b)

array([[-3.],
       [ 4.]])

<div class="alert alert-info">
<b> DİĞER İŞLEMLER </b> 
</div>

**Satır veya Sutün**

In [87]:
a = np.random.random((3,2))
print(a)

[[0.97895186 0.84960608]
 [0.50739784 0.50524309]
 [0.03444103 0.85124413]]


In [92]:
#satır toplamı
print(a.sum(axis=0))

[1.52079073 2.2060933 ]


In [93]:
#sutün toplamı
print(a.sum(axis=1))

[1.82855794 1.01264093 0.88568516]


**Minimum, maksimum**

In [96]:
a = np.random.random((3,2))
print(a)

[[0.39603909 0.90066008]
 [0.9138739  0.30872548]
 [0.25027729 0.7796466 ]]


In [97]:
print(a.min(axis=0))
print(a.min(axis=1))

[0.25027729 0.30872548]


In [99]:
print(a.max(axis=0))
print(a.max(axis=1))

[0.9138739  0.90066008]
[0.90066008 0.9138739  0.7796466 ]


**Maksimum veya minimum indeksleri bulma**

`argmin` ve `argmax` fonksiyonları ile yapılır

In [111]:
a = np.random.random((3,2))
print(a)

[[0.46851135 0.870479  ]
 [0.09518284 0.00370541]
 [0.60173065 0.91111836]]


In [112]:
# Flatten edilmiş haldeki indeksi verir
np.argmin(a)

3

In [113]:
#eğer indeksi 2 boyutlu istersek
np.unravel_index(np.argmin(a),a.shape)

(1, 1)

**Kümülatif toplam**

In [114]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [115]:
print(a.cumsum())

[ 0  1  3  6 10 15 21 28 36 45]


**Yeniden şekillendirme**<br>
Bir diziyi yeniden şekillendirebiliriz. Yani bir vektörü matrise çevirmemiz, matrisi yeniden boyutlandırmamız vb. mümkün. Bu amaçla temel olarak kullandığımız fonksiyon `reshape`tir

In [116]:
# Uzunluğu 9 olan bir vektör yaratalım
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [118]:
a_reshape = a.reshape(3,3)
print(a_reshape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [119]:
# Bu matrisi tekrar vektör haline getirelim
print(a_reshape.flatten())

[0 1 2 3 4 5 6 7 8]


In [120]:
# ravel metodu da flatten ile aynı işlemi yapar
print(a_reshape.ravel())

[0 1 2 3 4 5 6 7 8]


In [121]:
# a matrisinin değişmediğine dikkat edin lütfen
print("\na matrisi değişmedi")
print(a)


a matrisi değişmedi
[0 1 2 3 4 5 6 7 8]


>Dikkat: `resize` metodu da matrisi şekillendirir, fakat bu matrisin kendisini değiştirmektedir. 
    

In [122]:
a = np.arange(9)
print(a)

a.resize((3,3))
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Matrisleri birleştirme**<br>
Matris ve vektörleri yan yana veya üst üste eklemek için np.concatenate() fonksiyonunu kullanabiliriz.

In [124]:
A = np.array([[1,2],[3,4]])
print("\nA matrisi")
print(A)

B = np.array([[5,6],[7,8]])
print("\nB matrisi")
print(B)


A matrisi
[[1 2]
 [3 4]]

B matrisi
[[5 6]
 [7 8]]


>`vstack`

In [125]:
print("\nA ve B'yi alt alta ekleyelim")
print(np.concatenate([A,B]))


A ve B'yi alt alta ekleyelim
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [126]:
print("veya np.vstack() kullanalım")
print(np.vstack([A,B]))

veya np.vstack() kullanalım
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


>`hstack`

In [128]:
print("\nA ve B'yi yan yana ekleyelim")
print(np.concatenate([A,B],axis=1)) # axis=1


A ve B'yi yan yana ekleyelim
[[1 2 5 6]
 [3 4 7 8]]


In [129]:
print("veya np.hstack() kullanalım")
print(np.hstack([A,B]))

veya np.hstack() kullanalım
[[1 2 5 6]
 [3 4 7 8]]


>`row_stack` & `col_stack` 

In [131]:
# row_stack ve column_stack de bu amaçla kullanılabilir
print(np.row_stack([A,B]))
print(np.column_stack([A,B]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [132]:
# veya r_ ve c_ de kullabılabilir
# !!!! bu fonksiyon değildir dikkat
np.r_[A,B]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
np.c_[A,B]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Matrisleri ayırma**
<br> Matrisleri ayırmak için np.split() fonksiyonu kullanabiliriz.

In [134]:
C = np.array([[1,2,3,4],[5,6,7,8]])
print(C)
print("\n")

[[1 2 3 4]
 [5 6 7 8]]




In [135]:
print("Satır indeksine göre ayırma")
x,y = np.split(C, [1],axis=0)
print(x)
print(y)
print("\n")

Satır indeksine göre ayırma
[[1 2 3 4]]
[[5 6 7 8]]




In [136]:
print("Sütun indeksine göre ayırma")
x,y = np.split(C, [1],axis=1)
print(x)
print(y)

Sütun indeksine göre ayırma
[[1]
 [5]]
[[2 3 4]
 [6 7 8]]


`hsplit` ve `vsplit` de kullanılmaktadır. Bunlar `split` fonksiyonu ile aynıdır. Sadece `axis` parametresi değişmektedir.

In [137]:
a,b=np.hsplit(C,2)
print(a)
print(b)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Eksik ve sonsuz değerleri matrise ekleme**

Bazı durumlarda -örneğin bir matriste eksik bir değer varsa- bu değerin sayı olmadığını belirtmemiz gerekir.

* "not-a-number" değerleri temsil etmek için np.nan

Sonsuz değerleri de temsil etmek için 

* np.inf kullanılır

In [138]:
a = np.array([[0,np.nan],[1,np.inf]])
print(a)

[[ 0. nan]
 [ 1. inf]]


In [139]:
a.dtype

dtype('float64')

**Yegane(Unique) elemanların bulunması**

np.unique():dizideki yegane elemanları ve sayılarını(return_counts = True) bulur

In [143]:
a = np.array([1,1,2,2,3,3,4,4,6,6,4,42,24,75,4,41])
print(a)

[ 1  1  2  2  3  3  4  4  6  6  4 42 24 75  4 41]


In [144]:
u,c = np.unique(a,return_counts=True)
print("Dizideki yegane elemanlar")
print(u)
print("Dizideki yegane elemanların kaç adet oldukları")
print(c)

Dizideki yegane elemanlar
[ 1  2  3  4  6 24 41 42 75]
Dizideki yegane elemanların kaç adet oldukları
[2 2 2 4 2 1 1 1 1]


In [145]:
# Aynı işlemi set kullanarak da yapabiliriz.
set(a)

{1, 2, 3, 4, 6, 24, 41, 42, 75}

<div class="alert alert-info">
<b> İTERASYON </b> 
</div>

Tek boyutlu dizilerde iterasyon eleman üzerinden yapılır

In [147]:
a = np.arange(5)
print(a)
for i in a:
    print(i,end=" ")

[0 1 2 3 4]
0 1 2 3 4 

Çok boyutlu dizilerde ise ilk eksen üzerinden yapılır. Yani örnek vermek gerekirse eğer elimizde 2 boyutlu bir matris varsa bunun satırları üzerinde işlem yapılır.

In [148]:
a = np.reshape(np.arange(12),(3,2,2))
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [153]:
for row in a:
    #print(row)
    for c in row:
        print(c)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]


<div class="alert alert-info">
<b> DİĞER KONULAR </b> 
</div>

>Bir diziyi başka bir diziye eşitlediğinizde *kopyalanmaz* veri aynıdır. 

Kopyalama yapmak isterseniz bunu `copy()` metodunu kullanarak açıkça belirtmeniz lazım

In [155]:
a = np.arange(3)
print("a nın ilk değeri")
print(a)

a nın ilk değeri
[0 1 2]


In [156]:
# b'ye a'yı eşitledik
b = a
b[0] = 100
b

array([100,   1,   2])

In [157]:
# a'nın değeri de değişti aman dikkat
print("a nın son değeri")
print(a)

a nın son değeri
[100   1   2]


In [158]:
a = np.arange(3)
print("a nın ilk değeri")
print(a)

a nın ilk değeri
[0 1 2]


In [159]:
# b'ye a'yı eşitledik
b = a.copy()
b[0] = 100

In [160]:
# a'nın değeri şimdi değişmedi
print("a nın son değeri")
print(a)

a nın son değeri
[0 1 2]


In [161]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


>Broadcasting


Braodcasting, aritmetik işlemler sırasında farklı şekillerdeki dizileri işleme yeteneğini ifade eder.

In [162]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [163]:
v = np.array([100, 100, 100])
y = x + v
print(y)

[[101 102 103]
 [104 105 106]
 [107 108 109]
 [110 111 112]]
